CREATE DATABASE demo_db;
USE demo_db;

CREATE TABLE students (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  course VARCHAR(100) NOT NULL
);
